-- Initial migration for the Max Fitness Platform.
--
-- Part 1 is generated from prisma/schema.prisma.
-- Part 2 is hand-written SQL from prisma/sql/, which Prisma cannot express:
-- partial unique indexes, CHECK constraints, the v_member_fee read model, and
-- Row Level Security on every table (ADR-011). Do not edit this file after it
-- has been applied anywhere — create a new migration instead.

-- ═══ Part 1: generated from schema.prisma ═══

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateEnum
CREATE TYPE "StaffRole" AS ENUM ('OWNER', 'RECEPTION', 'TRAINER', 'SUPER_ADMIN');

-- CreateEnum
CREATE TYPE "Gender" AS ENUM ('MALE', 'FEMALE', 'OTHER');

-- CreateEnum
CREATE TYPE "MemberStatus" AS ENUM ('PENDING_PAYMENT', 'PENDING_VERIFICATION', 'ACTIVE', 'LEFT', 'BLOCKED');

-- CreateEnum
CREATE TYPE "MemberSource" AS ENUM ('WEBSITE', 'QR_NEW', 'QR_EXISTING', 'WALK_IN', 'IMPORT', 'CRM');

-- CreateEnum
CREATE TYPE "LeftReason" AS ENUM ('WHATSAPP_UNSUBSCRIBE', 'OWNER_MARKED', 'LAPSED', 'MOVED_AWAY', 'PRICE', 'HEALTH', 'NOT_SATISFIED', 'OTHER');

-- CreateEnum
CREATE TYPE "Language" AS ENUM ('hi', 'en');

-- CreateEnum
CREATE TYPE "MembershipStatus" AS ENUM ('PENDING_PAYMENT', 'CONFIRMED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "PaymentMethod" AS ENUM ('RAZORPAY', 'CASH', 'UPI_DIRECT', 'CARD_POS', 'BANK_TRANSFER', 'SIMULATED');

-- CreateEnum
CREATE TYPE "PaymentStatus" AS ENUM ('CREATED', 'PAID', 'FAILED', 'VOIDED', 'REFUNDED');

-- CreateEnum
CREATE TYPE "LeadStatus" AS ENUM ('NEW', 'CONTACTED', 'TRIAL_BOOKED', 'VISITED', 'CONVERTED', 'LOST');

-- CreateEnum
CREATE TYPE "LeadSource" AS ENUM ('WEBSITE_HERO', 'WEBSITE_OTHER', 'WHATSAPP', 'WALK_IN', 'PHONE', 'INSTAGRAM', 'GBP', 'REFERRAL', 'ABANDONED_SIGNUP');

-- CreateEnum
CREATE TYPE "VerificationStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED');

-- CreateEnum
CREATE TYPE "ConsentType" AS ENUM ('TERMS', 'PRIVACY', 'WHATSAPP_UPDATES', 'FACE_ATTENDANCE', 'PARENTAL', 'PHOTO_MARKETING');

-- CreateEnum
CREATE TYPE "MediaKind" AS ENUM ('SELFIE', 'ENROLLMENT_FRAME', 'RECEIPT_PDF', 'CHECKIN_SNAPSHOT', 'IMPORT_FILE');

-- CreateEnum
CREATE TYPE "FaceTemplateStatus" AS ENUM ('ACTIVE', 'REVOKED');

-- CreateEnum
CREATE TYPE "EnrollmentJobStatus" AS ENUM ('PENDING', 'IN_PROGRESS', 'DONE', 'FAILED');

-- CreateEnum
CREATE TYPE "AttendanceMethod" AS ENUM ('FACE', 'FACE_CONFIRMED', 'KEYPAD', 'MANUAL');

-- CreateEnum
CREATE TYPE "KioskStatus" AS ENUM ('ACTIVE', 'REVOKED');

-- CreateEnum
CREATE TYPE "MessageDirection" AS ENUM ('OUTBOUND', 'INBOUND');

-- CreateEnum
CREATE TYPE "MessageStatus" AS ENUM ('QUEUED', 'SENT', 'DELIVERED', 'READ', 'FAILED', 'SKIPPED', 'SIMULATED');

-- CreateEnum
CREATE TYPE "MessagePurpose" AS ENUM ('REMINDER', 'RECEIPT', 'WELCOME', 'VERIFICATION', 'OTP', 'OWNER_DIGEST', 'OWNER_ALERT', 'BIRTHDAY', 'UNSUBSCRIBE_CONFIRM', 'RESTART_CONFIRM', 'OTHER');

-- CreateEnum
CREATE TYPE "CallTaskReason" AS ENUM ('EXPIRED_BUT_VISITING', 'SIGNUP_NOT_PAID', 'NEW_LEAD', 'VERIFICATION_PENDING', 'EXPIRED_NOT_RENEWED', 'DUE_SOON_NO_RESPONSE', 'ABSENT_7_DAYS', 'UNSUBSCRIBED', 'OTHER');

-- CreateEnum
CREATE TYPE "TaskStatus" AS ENUM ('OPEN', 'DONE', 'SKIPPED', 'AUTO_CLOSED');

-- CreateEnum
CREATE TYPE "CallOutcome" AS ENUM ('WILL_RENEW', 'CALL_LATER', 'NO_ANSWER', 'LEFT_GYM', 'WRONG_NUMBER', 'DONE');

-- CreateEnum
CREATE TYPE "AlertType" AS ENUM ('EXPIRED_MEMBER_VISIT', 'ONLINE_PAYMENT', 'NEW_LEAD', 'VERIFICATION_PENDING', 'MEMBER_UNSUBSCRIBED', 'KIOSK_OFFLINE', 'WHATSAPP_FAILURE', 'WHATSAPP_QUALITY', 'SYSTEM');

-- CreateEnum
CREATE TYPE "OtpPurpose" AS ENUM ('SIGNUP', 'QR_EXISTING', 'CRM_LOGIN_RESET');

-- CreateEnum
CREATE TYPE "OutboxStatus" AS ENUM ('PENDING', 'DISPATCHED', 'FAILED');

-- CreateTable
CREATE TABLE "Gym" (
    "id" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "phone" TEXT NOT NULL,
    "addressLine" TEXT NOT NULL,
    "city" TEXT NOT NULL,
    "state" TEXT NOT NULL,
    "pincode" TEXT NOT NULL,
    "latitude" DOUBLE PRECISION,
    "longitude" DOUBLE PRECISION,
    "settings" JSONB NOT NULL,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "Gym_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Counter" (
    "id" TEXT NOT NULL,
    "gymId" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    "value" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "Counter_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "StaffUser" (
    "id" TEXT NOT NULL,
    "gymId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "mobile" TEXT NOT NULL,
    "role" "StaffRole" NOT NULL,
    "pinHash" TEXT NOT NULL,
    "language" "Language" NOT NULL DEFAULT 'hi',
    "voiceEnabled" BOOLEAN NOT NULL DEFAULT true,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "failedPinCount" INTEGER NOT NULL DEFAULT 0,
    "lockedUntil" TIMESTAMPTZ,
    "lastLoginAt" TIMESTAMPTZ,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "StaffUser_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Session" (
    "id" TEXT NOT NULL,
    "staffUserId" TEXT NOT NULL,
    "tokenHash" TEXT NOT NULL,
    "userAgent" TEXT,
    "ipHash" TEXT,
    "trusted" BOOLEAN NOT NULL DEFAULT false,
    "expiresAt" TIMESTAMPTZ NOT NULL,
    "lastSeenAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "revokedAt" TIMESTAMPTZ,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Session_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "OtpCode" (
    "id" TEXT NOT NULL,
    "gymId" TEXT NOT NULL,
    "mobile" TEXT NOT NULL,
    "purpose" "OtpPurpose" NOT NULL,
    "codeHash" TEXT NOT NULL,
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "expiresAt" TIMESTAMPTZ NOT NULL,
    "consumedAt" TIMESTAMPTZ,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "OtpCode_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Plan" (
    "id" TEXT NOT NULL,
    "gymId" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "durationMonths" INTEGER NOT NULL,
    "gender" "Gender" NOT NULL,
    "pricePaise" INTEGER NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "Plan_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Member" (
    "id" TEXT NOT NULL,
    "gymId" TEXT NOT NULL,
    "memberCode" TEXT,
    "fullName" TEXT NOT NULL,
    "mobile" TEXT NOT NULL,
    "email" TEXT,
    "dob" DATE,
    "gender" "Gender" NOT NULL,
    "language" "Language" NOT NULL DEFAULT 'hi',
    "status" "MemberStatus" NOT NULL,
    "source" "MemberSource" NOT NULL,
    "isMinor" BOOLEAN NOT NULL DEFAULT false,
    "photoMediaId" TEXT,
    "whatsappOptIn" BOOLEAN NOT NULL DEFAULT false,
    "faceConsent" BOOLEAN NOT NULL DEFAULT false,
    "remindersUnsubscribedAt" TIMESTAMPTZ,
    "remindersPausedUntil" DATE,
    "leftAt" DATE,
    "leftReason" "LeftReason",
    "leftNote" TEXT,
    "notes" TEXT,
    "lastAttendanceAt" TIMESTAMPTZ,
    "createdById" TEXT,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ NOT NULL,
    "deletedAt" TIMESTAMPTZ,

    CONSTRAINT "Member_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Membership" (
    "id" TEXT NOT NULL,
    "gymId" TEXT NOT NULL,
    "memberId" TEXT NOT NULL,
    "planId" TEXT,
    "durationMonths" INTEGER,
    "startDate" DATE,
    "endDate" DATE NOT NULL,
    "pricePaise" INTEGER NOT NULL DEFAULT 0,
    "discountPaise" INTEGER NOT NULL DEFAULT 0,
    "discountReason" TEXT,
    "admissionPaise" INTEGER NOT NULL DEFAULT 0,
    "status" "MembershipStatus" NOT NULL,
    "source" "MemberSource" NOT NULL,
    "isDeclared" BOOLEAN NOT NULL DEFAULT false,
    "declaredEndDate" DATE,
    "createdById" TEXT,
    "confirmedAt" TIMESTAMPTZ,
    "cancelledAt" TIMESTAMPTZ,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "Membership_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Payment" (
    "id" TEXT NOT NULL,
    "gymId" TEXT NOT NULL,
    "memberId" TEXT NOT NULL,
    "membershipId" TEXT,
    "amountPaise" INTEGER NOT NULL,
    "method" "PaymentMethod" NOT NULL,
    "status" "PaymentStatus" NOT NULL,
    "receiptNo" TEXT,
    "providerOrderId" TEXT,
    "providerPaymentId" TEXT,
    "providerSignatureOk" BOOLEAN NOT NULL DEFAULT false,
    "failureReason" TEXT,
    "paidAt" TIMESTAMPTZ,
    "recordedById" TEXT,
    "voidedById" TEXT,
    "voidReason" TEXT,
    "receiptMediaId" TEXT,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "Payment_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Lead" (
    "id" TEXT NOT NULL,
    "gymId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "mobile" TEXT NOT NULL,
    "goal" TEXT,
    "source" "LeadSource" NOT NULL,
    "status" "LeadStatus" NOT NULL DEFAULT 'NEW',
    "utm" JSONB,
    "notes" TEXT,
    "followUpAt" TIMESTAMPTZ,
    "convertedMemberId" TEXT,
    "consentContact" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "Lead_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "VerificationRequest" (
    "id" TEXT NOT NULL,
    "gymId" TEXT NOT NULL,
    "memberId" TEXT NOT NULL,
    "referenceCode" TEXT NOT NULL,
    "declaredPlanMonths" INTEGER,
    "declaredEndDate" DATE NOT NULL,
    "declaredAmountPaise" INTEGER,
    "matchedImportMemberId" TEXT,
    "status" "VerificationStatus" NOT NULL DEFAULT 'PENDING',
    "decidedById" TEXT,
    "decidedAt" TIMESTAMPTZ,
    "approvedEndDate" DATE,
    "rejectReason" TEXT,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "VerificationRequest_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "MediaFile" (
    "id" TEXT NOT NULL,
    "gymId" TEXT NOT NULL,
    "memberId" TEXT,
    "kind" "MediaKind" NOT NULL,
    "storageKey" TEXT NOT NULL,
    "mimeType" TEXT NOT NULL,
    "sizeBytes" INTEGER NOT NULL,
    "width" INTEGER,
    "height" INTEGER,
    "sha256" TEXT NOT NULL,
    "deleteAfter" TIMESTAMPTZ,
    "deletedAt" TIMESTAMPTZ,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "MediaFile_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Consent" (
    "id" TEXT NOT NULL,
    "gymId" TEXT NOT NULL,
    "memberId" TEXT NOT NULL,
    "type" "ConsentType" NOT NULL,
    "granted" BOOLEAN NOT NULL,
    "noticeVersion" TEXT NOT NULL,
    "channel" TEXT NOT NULL,
    "ipHash" TEXT,
    "userAgent" TEXT,
    "recordedById" TEXT,
    "guardianName" TEXT,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "withdrawnAt" TIMESTAMPTZ,

    CONSTRAINT "Consent_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "FaceTemplate" (
    "id" TEXT NOT NULL,
    "gymId" TEXT NOT NULL,
    "memberId" TEXT NOT NULL,
    "vectorEnc" BYTEA NOT NULL,
    "dimensions" INTEGER NOT NULL,
    "modelVersion" TEXT NOT NULL,
    "qualityScore" DOUBLE PRECISION NOT NULL,
    "sourceMediaId" TEXT,
    "sourceKind" TEXT NOT NULL,
    "createdByDevice" TEXT,
    "status" "FaceTemplateStatus" NOT NULL DEFAULT 'ACTIVE',
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "revokedAt" TIMESTAMPTZ,

    CONSTRAINT "FaceTemplate_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "EnrollmentJob" (
    "id" TEXT NOT NULL,
    "gymId" TEXT NOT NULL,
    "memberId" TEXT NOT NULL,
    "mediaId" TEXT NOT NULL,
    "modelVersion" TEXT NOT NULL,
    "status" "EnrollmentJobStatus" NOT NULL DEFAULT 'PENDING',
    "claimedBy" TEXT,
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "error" TEXT,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "EnrollmentJob_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "KioskDevice" (
    "id" TEXT NOT NULL,
    "gymId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "tokenHash" TEXT,
    "pairingCodeHash" TEXT,
    "pairingExpires" TIMESTAMPTZ,
    "status" "KioskStatus" NOT NULL DEFAULT 'ACTIVE',
    "appVersion" TEXT,
    "modelVersion" TEXT,
    "lastSeenAt" TIMESTAMPTZ,
    "lastHeartbeat" JSONB,
    "shadowMode" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "revokedAt" TIMESTAMPTZ,

    CONSTRAINT "KioskDevice_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AttendanceEvent" (
    "id" TEXT NOT NULL,
    "gymId" TEXT NOT NULL,
    "memberId" TEXT NOT NULL,
    "kioskDeviceId" TEXT,
    "clientEventId" TEXT NOT NULL,
    "method" "AttendanceMethod" NOT NULL,
    "capturedAt" TIMESTAMPTZ NOT NULL,
    "attendanceDate" DATE NOT NULL,
    "matchScore" DOUBLE PRECISION,
    "livenessScore" DOUBLE PRECISION,
    "modelVersion" TEXT,
    "feeStateAtCheckIn" TEXT,
    "snapshotMediaId" TEXT,
    "recordedById" TEXT,
    "voidedAt" TIMESTAMPTZ,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AttendanceEvent_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ReminderRule" (
    "id" TEXT NOT NULL,
    "gymId" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "offsetDays" INTEGER NOT NULL,
    "offsetDaysTo" INTEGER,
    "slots" TEXT[],
    "templateName" TEXT NOT NULL,
    "isEnabled" BOOLEAN NOT NULL DEFAULT true,
    "updatedAt" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "ReminderRule_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "MessageLog" (
    "id" TEXT NOT NULL,
    "gymId" TEXT NOT NULL,
    "memberId" TEXT,
    "membershipId" TEXT,
    "direction" "MessageDirection" NOT NULL,
    "purpose" "MessagePurpose" NOT NULL,
    "ruleCode" TEXT,
    "templateName" TEXT,
    "language" "Language",
    "toNumber" TEXT,
    "fromNumber" TEXT,
    "idempotencyKey" TEXT,
    "providerMessageId" TEXT,
    "status" "MessageStatus" NOT NULL,
    "bodyPreview" TEXT,
    "payload" JSONB,
    "errorCode" TEXT,
    "errorMessage" TEXT,
    "scheduledFor" TIMESTAMPTZ,
    "sentAt" TIMESTAMPTZ,
    "deliveredAt" TIMESTAMPTZ,
    "readAt" TIMESTAMPTZ,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "MessageLog_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "WebhookEvent" (
    "id" TEXT NOT NULL,
    "gymId" TEXT,
    "provider" TEXT NOT NULL,
    "externalId" TEXT NOT NULL,
    "eventType" TEXT NOT NULL,
    "signatureOk" BOOLEAN NOT NULL,
    "payload" JSONB NOT NULL,
    "processedAt" TIMESTAMPTZ,
    "error" TEXT,
    "receivedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "WebhookEvent_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "CallTask" (
    "id" TEXT NOT NULL,
    "gymId" TEXT NOT NULL,
    "memberId" TEXT,
    "leadId" TEXT,
    "reason" "CallTaskReason" NOT NULL,
    "priority" INTEGER NOT NULL,
    "status" "TaskStatus" NOT NULL DEFAULT 'OPEN',
    "dueDate" DATE NOT NULL,
    "snoozedUntil" DATE,
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "outcome" "CallOutcome",
    "note" TEXT,
    "doneById" TEXT,
    "doneAt" TIMESTAMPTZ,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "CallTask_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Alert" (
    "id" TEXT NOT NULL,
    "gymId" TEXT NOT NULL,
    "type" "AlertType" NOT NULL,
    "memberId" TEXT,
    "title" TEXT NOT NULL,
    "params" JSONB,
    "readAt" TIMESTAMPTZ,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Alert_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AuditLog" (
    "id" TEXT NOT NULL,
    "gymId" TEXT NOT NULL,
    "actorType" TEXT NOT NULL,
    "actorId" TEXT,
    "action" TEXT NOT NULL,
    "entityType" TEXT NOT NULL,
    "entityId" TEXT,
    "before" JSONB,
    "after" JSONB,
    "ipHash" TEXT,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AuditLog_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "OutboxEvent" (
    "id" TEXT NOT NULL,
    "gymId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "payload" JSONB NOT NULL,
    "dedupeKey" TEXT NOT NULL,
    "status" "OutboxStatus" NOT NULL DEFAULT 'PENDING',
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "lastError" TEXT,
    "availableAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "dispatchedAt" TIMESTAMPTZ,

    CONSTRAINT "OutboxEvent_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "WorkerHeartbeat" (
    "id" TEXT NOT NULL,
    "version" TEXT NOT NULL,
    "lastBeatAt" TIMESTAMPTZ NOT NULL,
    "startedAt" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "WorkerHeartbeat_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "JobRun" (
    "id" TEXT NOT NULL,
    "gymId" TEXT,
    "jobName" TEXT NOT NULL,
    "runKey" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "itemsPlanned" INTEGER NOT NULL DEFAULT 0,
    "itemsSent" INTEGER NOT NULL DEFAULT 0,
    "itemsSkipped" INTEGER NOT NULL DEFAULT 0,
    "itemsFailed" INTEGER NOT NULL DEFAULT 0,
    "error" TEXT,
    "startedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "finishedAt" TIMESTAMPTZ,

    CONSTRAINT "JobRun_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Gym_slug_key" ON "Gym"("slug");

-- CreateIndex
CREATE UNIQUE INDEX "Counter_gymId_key_key" ON "Counter"("gymId", "key");

-- CreateIndex
CREATE UNIQUE INDEX "StaffUser_gymId_mobile_key" ON "StaffUser"("gymId", "mobile");

-- CreateIndex
CREATE UNIQUE INDEX "Session_tokenHash_key" ON "Session"("tokenHash");

-- CreateIndex
CREATE INDEX "Session_staffUserId_idx" ON "Session"("staffUserId");

-- CreateIndex
CREATE INDEX "OtpCode_gymId_mobile_purpose_idx" ON "OtpCode"("gymId", "mobile", "purpose");

-- CreateIndex
CREATE INDEX "Plan_gymId_gender_isActive_idx" ON "Plan"("gymId", "gender", "isActive");

-- CreateIndex
CREATE UNIQUE INDEX "Plan_gymId_code_key" ON "Plan"("gymId", "code");

-- CreateIndex
CREATE UNIQUE INDEX "Member_photoMediaId_key" ON "Member"("photoMediaId");

-- CreateIndex
CREATE INDEX "Member_gymId_status_idx" ON "Member"("gymId", "status");

-- CreateIndex
CREATE INDEX "Member_gymId_mobile_idx" ON "Member"("gymId", "mobile");

-- CreateIndex
CREATE INDEX "Member_gymId_fullName_idx" ON "Member"("gymId", "fullName");

-- CreateIndex
CREATE UNIQUE INDEX "Member_gymId_memberCode_key" ON "Member"("gymId", "memberCode");

-- CreateIndex
CREATE INDEX "Membership_gymId_status_endDate_idx" ON "Membership"("gymId", "status", "endDate");

-- CreateIndex
CREATE INDEX "Membership_memberId_endDate_idx" ON "Membership"("memberId", "endDate");

-- CreateIndex
CREATE UNIQUE INDEX "Payment_providerOrderId_key" ON "Payment"("providerOrderId");

-- CreateIndex
CREATE UNIQUE INDEX "Payment_providerPaymentId_key" ON "Payment"("providerPaymentId");

-- CreateIndex
CREATE INDEX "Payment_gymId_status_paidAt_idx" ON "Payment"("gymId", "status", "paidAt");

-- CreateIndex
CREATE INDEX "Payment_memberId_idx" ON "Payment"("memberId");

-- CreateIndex
CREATE UNIQUE INDEX "Payment_gymId_receiptNo_key" ON "Payment"("gymId", "receiptNo");

-- CreateIndex
CREATE INDEX "Lead_gymId_status_createdAt_idx" ON "Lead"("gymId", "status", "createdAt");

-- CreateIndex
CREATE INDEX "Lead_gymId_mobile_idx" ON "Lead"("gymId", "mobile");

-- CreateIndex
CREATE INDEX "VerificationRequest_gymId_status_createdAt_idx" ON "VerificationRequest"("gymId", "status", "createdAt");

-- CreateIndex
CREATE UNIQUE INDEX "VerificationRequest_gymId_referenceCode_key" ON "VerificationRequest"("gymId", "referenceCode");

-- CreateIndex
CREATE UNIQUE INDEX "MediaFile_storageKey_key" ON "MediaFile"("storageKey");

-- CreateIndex
CREATE INDEX "MediaFile_gymId_kind_idx" ON "MediaFile"("gymId", "kind");

-- CreateIndex
CREATE INDEX "MediaFile_memberId_idx" ON "MediaFile"("memberId");

-- CreateIndex
CREATE INDEX "Consent_memberId_type_idx" ON "Consent"("memberId", "type");

-- CreateIndex
CREATE INDEX "FaceTemplate_gymId_status_modelVersion_idx" ON "FaceTemplate"("gymId", "status", "modelVersion");

-- CreateIndex
CREATE INDEX "FaceTemplate_memberId_idx" ON "FaceTemplate"("memberId");

-- CreateIndex
CREATE INDEX "EnrollmentJob_gymId_status_idx" ON "EnrollmentJob"("gymId", "status");

-- CreateIndex
CREATE UNIQUE INDEX "KioskDevice_tokenHash_key" ON "KioskDevice"("tokenHash");

-- CreateIndex
CREATE UNIQUE INDEX "AttendanceEvent_clientEventId_key" ON "AttendanceEvent"("clientEventId");

-- CreateIndex
CREATE INDEX "AttendanceEvent_gymId_attendanceDate_idx" ON "AttendanceEvent"("gymId", "attendanceDate");

-- CreateIndex
CREATE INDEX "AttendanceEvent_memberId_capturedAt_idx" ON "AttendanceEvent"("memberId", "capturedAt");

-- CreateIndex
CREATE UNIQUE INDEX "ReminderRule_gymId_code_key" ON "ReminderRule"("gymId", "code");

-- CreateIndex
CREATE UNIQUE INDEX "MessageLog_idempotencyKey_key" ON "MessageLog"("idempotencyKey");

-- CreateIndex
CREATE UNIQUE INDEX "MessageLog_providerMessageId_key" ON "MessageLog"("providerMessageId");

-- CreateIndex
CREATE INDEX "MessageLog_gymId_createdAt_idx" ON "MessageLog"("gymId", "createdAt");

-- CreateIndex
CREATE INDEX "MessageLog_memberId_createdAt_idx" ON "MessageLog"("memberId", "createdAt");

-- CreateIndex
CREATE INDEX "MessageLog_gymId_status_idx" ON "MessageLog"("gymId", "status");

-- CreateIndex
CREATE INDEX "WebhookEvent_provider_processedAt_idx" ON "WebhookEvent"("provider", "processedAt");

-- CreateIndex
CREATE UNIQUE INDEX "WebhookEvent_provider_externalId_key" ON "WebhookEvent"("provider", "externalId");

-- CreateIndex
CREATE INDEX "CallTask_gymId_status_dueDate_priority_idx" ON "CallTask"("gymId", "status", "dueDate", "priority");

-- CreateIndex
CREATE INDEX "CallTask_memberId_reason_status_idx" ON "CallTask"("memberId", "reason", "status");

-- CreateIndex
CREATE INDEX "Alert_gymId_readAt_createdAt_idx" ON "Alert"("gymId", "readAt", "createdAt");

-- CreateIndex
CREATE INDEX "AuditLog_gymId_entityType_entityId_idx" ON "AuditLog"("gymId", "entityType", "entityId");

-- CreateIndex
CREATE INDEX "AuditLog_gymId_createdAt_idx" ON "AuditLog"("gymId", "createdAt");

-- CreateIndex
CREATE UNIQUE INDEX "OutboxEvent_dedupeKey_key" ON "OutboxEvent"("dedupeKey");

-- CreateIndex
CREATE INDEX "OutboxEvent_status_availableAt_idx" ON "OutboxEvent"("status", "availableAt");

-- CreateIndex
CREATE UNIQUE INDEX "JobRun_jobName_runKey_key" ON "JobRun"("jobName", "runKey");

-- AddForeignKey
ALTER TABLE "Counter" ADD CONSTRAINT "Counter_gymId_fkey" FOREIGN KEY ("gymId") REFERENCES "Gym"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "StaffUser" ADD CONSTRAINT "StaffUser_gymId_fkey" FOREIGN KEY ("gymId") REFERENCES "Gym"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Session" ADD CONSTRAINT "Session_staffUserId_fkey" FOREIGN KEY ("staffUserId") REFERENCES "StaffUser"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "OtpCode" ADD CONSTRAINT "OtpCode_gymId_fkey" FOREIGN KEY ("gymId") REFERENCES "Gym"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Plan" ADD CONSTRAINT "Plan_gymId_fkey" FOREIGN KEY ("gymId") REFERENCES "Gym"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Member" ADD CONSTRAINT "Member_gymId_fkey" FOREIGN KEY ("gymId") REFERENCES "Gym"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Member" ADD CONSTRAINT "Member_photoMediaId_fkey" FOREIGN KEY ("photoMediaId") REFERENCES "MediaFile"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Membership" ADD CONSTRAINT "Membership_gymId_fkey" FOREIGN KEY ("gymId") REFERENCES "Gym"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Membership" ADD CONSTRAINT "Membership_memberId_fkey" FOREIGN KEY ("memberId") REFERENCES "Member"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Membership" ADD CONSTRAINT "Membership_planId_fkey" FOREIGN KEY ("planId") REFERENCES "Plan"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Payment" ADD CONSTRAINT "Payment_gymId_fkey" FOREIGN KEY ("gymId") REFERENCES "Gym"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Payment" ADD CONSTRAINT "Payment_memberId_fkey" FOREIGN KEY ("memberId") REFERENCES "Member"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Payment" ADD CONSTRAINT "Payment_membershipId_fkey" FOREIGN KEY ("membershipId") REFERENCES "Membership"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Lead" ADD CONSTRAINT "Lead_gymId_fkey" FOREIGN KEY ("gymId") REFERENCES "Gym"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VerificationRequest" ADD CONSTRAINT "VerificationRequest_gymId_fkey" FOREIGN KEY ("gymId") REFERENCES "Gym"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VerificationRequest" ADD CONSTRAINT "VerificationRequest_memberId_fkey" FOREIGN KEY ("memberId") REFERENCES "Member"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MediaFile" ADD CONSTRAINT "MediaFile_gymId_fkey" FOREIGN KEY ("gymId") REFERENCES "Gym"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MediaFile" ADD CONSTRAINT "MediaFile_memberId_fkey" FOREIGN KEY ("memberId") REFERENCES "Member"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Consent" ADD CONSTRAINT "Consent_gymId_fkey" FOREIGN KEY ("gymId") REFERENCES "Gym"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Consent" ADD CONSTRAINT "Consent_memberId_fkey" FOREIGN KEY ("memberId") REFERENCES "Member"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FaceTemplate" ADD CONSTRAINT "FaceTemplate_gymId_fkey" FOREIGN KEY ("gymId") REFERENCES "Gym"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FaceTemplate" ADD CONSTRAINT "FaceTemplate_memberId_fkey" FOREIGN KEY ("memberId") REFERENCES "Member"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EnrollmentJob" ADD CONSTRAINT "EnrollmentJob_gymId_fkey" FOREIGN KEY ("gymId") REFERENCES "Gym"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EnrollmentJob" ADD CONSTRAINT "EnrollmentJob_memberId_fkey" FOREIGN KEY ("memberId") REFERENCES "Member"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "KioskDevice" ADD CONSTRAINT "KioskDevice_gymId_fkey" FOREIGN KEY ("gymId") REFERENCES "Gym"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AttendanceEvent" ADD CONSTRAINT "AttendanceEvent_gymId_fkey" FOREIGN KEY ("gymId") REFERENCES "Gym"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AttendanceEvent" ADD CONSTRAINT "AttendanceEvent_memberId_fkey" FOREIGN KEY ("memberId") REFERENCES "Member"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AttendanceEvent" ADD CONSTRAINT "AttendanceEvent_kioskDeviceId_fkey" FOREIGN KEY ("kioskDeviceId") REFERENCES "KioskDevice"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ReminderRule" ADD CONSTRAINT "ReminderRule_gymId_fkey" FOREIGN KEY ("gymId") REFERENCES "Gym"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MessageLog" ADD CONSTRAINT "MessageLog_gymId_fkey" FOREIGN KEY ("gymId") REFERENCES "Gym"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MessageLog" ADD CONSTRAINT "MessageLog_memberId_fkey" FOREIGN KEY ("memberId") REFERENCES "Member"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MessageLog" ADD CONSTRAINT "MessageLog_membershipId_fkey" FOREIGN KEY ("membershipId") REFERENCES "Membership"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "WebhookEvent" ADD CONSTRAINT "WebhookEvent_gymId_fkey" FOREIGN KEY ("gymId") REFERENCES "Gym"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CallTask" ADD CONSTRAINT "CallTask_gymId_fkey" FOREIGN KEY ("gymId") REFERENCES "Gym"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CallTask" ADD CONSTRAINT "CallTask_memberId_fkey" FOREIGN KEY ("memberId") REFERENCES "Member"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Alert" ADD CONSTRAINT "Alert_gymId_fkey" FOREIGN KEY ("gymId") REFERENCES "Gym"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Alert" ADD CONSTRAINT "Alert_memberId_fkey" FOREIGN KEY ("memberId") REFERENCES "Member"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_gymId_fkey" FOREIGN KEY ("gymId") REFERENCES "Gym"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "OutboxEvent" ADD CONSTRAINT "OutboxEvent_gymId_fkey" FOREIGN KEY ("gymId") REFERENCES "Gym"("id") ON DELETE RESTRICT ON UPDATE CASCADE;


-- ═══ Part 2: prisma/sql/01-constraints-and-rls.sql ═══

-- ─────────────────────────────────────────────────────────────────────────────
-- Hand-written SQL appended to the first migration.
--
-- Prisma cannot express partial unique indexes, CHECK constraints, expression
-- indexes, views or RLS, so these live here and are concatenated onto the
-- generated `migration.sql` (database-design.md §3, §4.1, §10.2).
--
-- Keep this file as the source of truth: `pnpm db:migrate` appends it, and a
-- reviewer can diff it without reading a generated file.
-- ─────────────────────────────────────────────────────────────────────────────


-- ── 1. Constraints Prisma cannot express (database-design.md §3) ─────────────

-- BR-7: at most one OPEN call task per (member, reason). Enforced in the service
-- *and* here, because a race between the nightly job and an event handler would
-- otherwise put the same call on the owner's list twice.
CREATE UNIQUE INDEX "calltask_open_member_reason"
  ON "CallTask" ("memberId", "reason")
  WHERE "status" = 'OPEN' AND "memberId" IS NOT NULL;

-- Money never negative. CLAUDE.md §2.1 puts money in integer paise; these make a
-- nonsensical amount impossible to store even if a bug reaches the insert.
ALTER TABLE "Payment"    ADD CONSTRAINT "payment_amount_positive" CHECK ("amountPaise" > 0);
ALTER TABLE "Plan"       ADD CONSTRAINT "plan_price_positive"     CHECK ("pricePaise" > 0);

-- BR-3.6 allows a declared membership with no start date, so the check has to
-- tolerate NULL rather than demand an ordering.
ALTER TABLE "Membership" ADD CONSTRAINT "membership_dates_valid"
  CHECK ("startDate" IS NULL OR "startDate" <= "endDate");

-- BR-8.1: the birthday list runs every morning over every active member, so the
-- month/day extraction needs an index of its own.
CREATE INDEX "member_dob_month_day"
  ON "Member" ((EXTRACT(MONTH FROM "dob")), (EXTRACT(DAY FROM "dob")))
  WHERE "status" = 'ACTIVE' AND "deletedAt" IS NULL;

-- Case-insensitive name search for the CRM member list.
CREATE INDEX "member_name_lower" ON "Member" (lower("fullName"));


-- ── 2. Fee-state read model (database-design.md §4.1) ────────────────────────
--
-- ADR-013: `feeState()` in packages/core is the canonical implementation. This
-- view exists only so list screens and dashboard counts are one indexed query
-- instead of N. An integration test diffs the two over the same fixtures; if they
-- disagree, the view is the bug.
--
-- ADR-014: the view takes the confirmed membership with the greatest endDate. That
-- is correct while renewals chain contiguously (BR-3.4/3.5) but would report PAID
-- for a member whose membership lapsed months ago and who has a booking starting
-- next year. Core applies the stricter reading; consumers of this view must not
-- make an irreversible decision (a send, a call task) on it alone.

CREATE VIEW "v_member_fee" AS
WITH confirmed AS (
  SELECT
    m.*,
    ROW_NUMBER() OVER (PARTITION BY m."memberId" ORDER BY m."endDate" DESC) AS rn
  FROM "Membership" m
  WHERE m."status" = 'CONFIRMED'
)
SELECT
  mem."id"                                                     AS "memberId",
  mem."gymId",
  c."id"                                                       AS "latestMembershipId",
  c."endDate"                                                  AS "effectiveEndDate",
  (c."endDate" - (now() AT TIME ZONE 'Asia/Kolkata')::date)     AS "daysLeft",
  CASE
    WHEN c."id" IS NULL                                              THEN 'NONE'
    WHEN (now() AT TIME ZONE 'Asia/Kolkata')::date > c."endDate"     THEN 'EXPIRED'
    WHEN c."endDate" - (now() AT TIME ZONE 'Asia/Kolkata')::date <= 7 THEN 'DUE_SOON'
    ELSE 'PAID'
  END                                                          AS "feeState"
FROM "Member" mem
LEFT JOIN confirmed c ON c."memberId" = mem."id" AND c.rn = 1
WHERE mem."deletedAt" IS NULL;

-- A date-parameterised twin of the view, so integration tests can pin "today"
-- instead of depending on the wall clock (testing-strategy.md §2, ADR-013).
CREATE FUNCTION "member_fee_at"(p_today date)
RETURNS TABLE (
  "memberId" text,
  "gymId" text,
  "latestMembershipId" text,
  "effectiveEndDate" date,
  "daysLeft" integer,
  "feeState" text
)
LANGUAGE sql
STABLE
AS $$
  WITH confirmed AS (
    SELECT m.*, ROW_NUMBER() OVER (PARTITION BY m."memberId" ORDER BY m."endDate" DESC) AS rn
    FROM "Membership" m
    WHERE m."status" = 'CONFIRMED'
  )
  SELECT
    mem."id",
    mem."gymId",
    c."id",
    c."endDate",
    (c."endDate" - p_today)::integer,
    CASE
      WHEN c."id" IS NULL                     THEN 'NONE'
      WHEN p_today > c."endDate"              THEN 'EXPIRED'
      WHEN c."endDate" - p_today <= 7         THEN 'DUE_SOON'
      ELSE 'PAID'
    END
  FROM "Member" mem
  LEFT JOIN confirmed c ON c."memberId" = mem."id" AND c.rn = 1
  WHERE mem."deletedAt" IS NULL;
$$;


-- ── 3. Row Level Security (ADR-011, security-plan.md §3.6) ───────────────────
--
-- Supabase auto-generates a PostgREST "Data API" over the public schema, callable
-- by anyone holding the project's anon key. We do not use it and it must expose
-- nothing.
--
-- Enabling RLS with NO policies denies every row to the `anon` and `authenticated`
-- roles PostgREST connects as. Our Prisma role owns these tables, and a table
-- owner bypasses RLS unless FORCE ROW LEVEL SECURITY is set — which we
-- deliberately do not set — so the application is entirely unaffected.
--
-- This is the second line of defence. The first is clearing `public` from the Data
-- API's exposed schemas in the Supabase dashboard, which is a manual step.
--
-- EVERY future migration that adds a table to `public` must add its ALTER here.
-- A forgotten line silently publishes a table.

ALTER TABLE "Gym"                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Counter"             ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StaffUser"           ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Session"             ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OtpCode"             ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Plan"                ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Member"              ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Membership"          ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Payment"             ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Lead"                ENABLE ROW LEVEL SECURITY;
ALTER TABLE "VerificationRequest" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MediaFile"           ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Consent"             ENABLE ROW LEVEL SECURITY;
ALTER TABLE "FaceTemplate"        ENABLE ROW LEVEL SECURITY;
ALTER TABLE "EnrollmentJob"       ENABLE ROW LEVEL SECURITY;
ALTER TABLE "KioskDevice"         ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AttendanceEvent"     ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ReminderRule"        ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MessageLog"          ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WebhookEvent"        ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CallTask"            ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Alert"               ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AuditLog"            ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OutboxEvent"         ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WorkerHeartbeat"     ENABLE ROW LEVEL SECURITY;
ALTER TABLE "JobRun"              ENABLE ROW LEVEL SECURITY;

-- Prisma creates `_prisma_migrations` in public before running any migration, so it
-- is not covered by the list above — and the Data API would otherwise expose the
-- migration history. Guarded, because the table name is Prisma's, not ours.
DO $$
BEGIN
  IF to_regclass('public._prisma_migrations') IS NOT NULL THEN
    ALTER TABLE public."_prisma_migrations" ENABLE ROW LEVEL SECURITY;
  END IF;
END
$$;

-- The view runs with the privileges of its owner, so it would otherwise be a way
-- around the tables' RLS. `security_invoker` makes it respect the caller's
-- permissions instead.
ALTER VIEW "v_member_fee" SET (security_invoker = true);

-- Revoke the blanket grants Supabase's default privileges hand to the API roles.
-- RLS alone already denies every row; this removes the grant as well, so an
-- anon-key request gets "permission denied" rather than an empty result.
--
-- Guarded on role existence: `anon` and `authenticated` are Supabase's roles and do
-- not exist on the plain Postgres 17 service container CI runs migrations against,
-- where an unguarded REVOKE would abort the migration.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
    REVOKE ALL ON ALL TABLES    IN SCHEMA public FROM anon;
    REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon;
    REVOKE ALL ON ALL FUNCTIONS IN SCHEMA public FROM anon;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM anon;
  END IF;

  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    REVOKE ALL ON ALL TABLES    IN SCHEMA public FROM authenticated;
    REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM authenticated;
    REVOKE ALL ON ALL FUNCTIONS IN SCHEMA public FROM authenticated;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM authenticated;
  END IF;
END
$$;

