import { readFileSync } from 'node:fs';
import type { Gender, Language, PlanDurationMonths } from '@mfp/shared';

/**
 * Reads `assets/demo-data/members_demo.csv` — 220 realistic people, each tagged
 * with the scenario the seed should build for them (demo-data-seed-spec.md §3).
 *
 * A tiny hand-rolled parser rather than a CSV library: this file is generated by
 * us, has no embedded newlines, and adding a dependency to read one known file
 * would be the wrong trade. It does handle quoted fields, because a name or note
 * containing a comma is plausible.
 */

export const SCENARIOS = [
  'ACTIVE_HEALTHY',
  'DUE_7',
  'DUE_3',
  'DUE_2',
  'DUE_1',
  'DUE_TODAY',
  'EXPIRED_1_3',
  'EXPIRED_4_7',
  'EXPIRED_BUT_VISITING',
  'EXPIRED_8_40',
  'LEFT_UNSUBSCRIBED',
  'LEFT_OWNER',
  'RENEWED_EARLY',
  'PENDING_VERIFICATION',
  'PENDING_PAYMENT',
  'BIRTHDAY_TODAY',
  'BIRTHDAY_WEEK',
  'ABSENT_10',
  'MINOR_GUARDIAN_PENDING',
  'SHARED_NUMBER_PAIR',
  'PAUSED_REMINDERS',
] as const;
export type Scenario = (typeof SCENARIOS)[number];

/** Visit frequency, which drives how much attendance history a member gets (§5). */
export const PERSONAS = ['REGULAR', 'MODERATE', 'IRREGULAR'] as const;
export type Persona = (typeof PERSONAS)[number];

export interface DemoMemberRow {
  readonly memberRef: string;
  readonly fullName: string;
  readonly gender: Gender;
  readonly mobile: string;
  readonly email: string | null;
  /** Only the birth year is in the CSV; the seed picks a month and day (§3). */
  readonly dobYear: number;
  readonly planMonths: PlanDurationMonths;
  readonly joinedYear: number;
  readonly scenario: Scenario;
  readonly language: Language;
  readonly whatsappOptIn: boolean;
  readonly faceConsent: boolean;
  readonly persona: Persona;
  readonly notes: string | null;
}

function splitCsvLine(line: string): string[] {
  const fields: string[] = [];
  let current = '';
  let inQuotes = false;

  for (let i = 0; i < line.length; i += 1) {
    const ch = line[i];
    if (inQuotes) {
      if (ch === '"') {
        if (line[i + 1] === '"') {
          current += '"';
          i += 1;
        } else {
          inQuotes = false;
        }
      } else {
        current += ch;
      }
    } else if (ch === '"') {
      inQuotes = true;
    } else if (ch === ',') {
      fields.push(current);
      current = '';
    } else {
      current += ch;
    }
  }
  fields.push(current);
  return fields.map((f) => f.trim());
}

function isScenario(value: string): value is Scenario {
  return (SCENARIOS as readonly string[]).includes(value);
}

function isPersona(value: string): value is Persona {
  return (PERSONAS as readonly string[]).includes(value);
}

export function loadDemoMembers(csvPath: string): DemoMemberRow[] {
  const text = readFileSync(csvPath, 'utf8').replace(/^\uFEFF/, '');
  const lines = text.split(/\r?\n/).filter((l) => l.trim().length > 0);

  const header = lines[0];
  if (header === undefined) {
    throw new Error(`${csvPath} is empty`);
  }
  const columns = splitCsvLine(header);
  const indexOf = (name: string): number => {
    const i = columns.indexOf(name);
    if (i === -1) throw new Error(`${csvPath} is missing the "${name}" column`);
    return i;
  };

  const col = {
    ref: indexOf('member_ref'),
    name: indexOf('full_name'),
    gender: indexOf('gender'),
    mobile: indexOf('mobile'),
    email: indexOf('email'),
    dobYear: indexOf('dob_year'),
    planMonths: indexOf('plan_months'),
    joinedYear: indexOf('joined_year'),
    scenario: indexOf('scenario'),
    language: indexOf('language'),
    optIn: indexOf('whatsapp_opt_in'),
    faceConsent: indexOf('face_consent'),
    persona: indexOf('persona'),
    notes: indexOf('notes'),
  };

  return lines.slice(1).map((line, rowIndex) => {
    const f = splitCsvLine(line);
    const at = (index: number): string => f[index] ?? '';
    const where = `${csvPath}:${rowIndex + 2}`;

    const scenario = at(col.scenario);
    if (!isScenario(scenario)) {
      throw new Error(`${where}: unknown scenario "${scenario}"`);
    }

    const persona = at(col.persona);
    if (!isPersona(persona)) {
      throw new Error(`${where}: unknown persona "${persona}"`);
    }

    const planMonths = Number(at(col.planMonths));
    if (![1, 3, 6, 12].includes(planMonths)) {
      throw new Error(`${where}: plan_months must be 1, 3, 6 or 12, got "${at(col.planMonths)}"`);
    }

    const genderCode = at(col.gender).toUpperCase();
    const gender: Gender = genderCode === 'F' ? 'FEMALE' : genderCode === 'M' ? 'MALE' : 'OTHER';

    const email = at(col.email);

    return {
      memberRef: at(col.ref),
      fullName: at(col.name),
      gender,
      mobile: at(col.mobile),
      email: email.length === 0 ? null : email.toLowerCase(),
      dobYear: Number(at(col.dobYear)),
      planMonths: planMonths as PlanDurationMonths,
      joinedYear: Number(at(col.joinedYear)),
      scenario,
      language: at(col.language) === 'en' ? 'en' : 'hi',
      whatsappOptIn: at(col.optIn) === 'true',
      faceConsent: at(col.faceConsent) === 'true',
      persona,
      notes: at(col.notes).length === 0 ? null : at(col.notes),
    };
  });
}

/** Group rows by scenario, for building each cohort in one pass. */
export function byScenario(rows: readonly DemoMemberRow[]): Map<Scenario, DemoMemberRow[]> {
  const map = new Map<Scenario, DemoMemberRow[]>();
  for (const row of rows) {
    const list = map.get(row.scenario);
    if (list === undefined) {
      map.set(row.scenario, [row]);
    } else {
      list.push(row);
    }
  }
  return map;
}
