/**
 * Builds the initial migration from the Prisma schema plus our hand-written SQL.
 *
 * `prisma migrate dev` would normally generate the table DDL for us, but it needs
 * a live database (and a shadow database) to do it. `prisma migrate diff
 * --from-empty` produces exactly the same DDL offline, which means the migration
 * can be written, reviewed and committed without a connection — and crucially,
 * without the RLS statements being an afterthought applied later (ADR-011).
 *
 * The output is a single migration containing:
 *   1. the generated CREATE TYPE / CREATE TABLE / CREATE INDEX statements, then
 *   2. `prisma/sql/01-constraints-and-rls.sql` — partial indexes, CHECK
 *      constraints, the fee-state view and function, and RLS on every table.
 *
 * Run it once. After that, new migrations come from `prisma migrate dev` as usual,
 * and each must carry its own `ENABLE ROW LEVEL SECURITY` for any table it adds.
 *
 *   pnpm --filter @mfp/db run db:build-initial-migration
 */
import { execFileSync } from 'node:child_process';
import { createRequire } from 'node:module';
import { existsSync, mkdirSync, readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const migrationsDir = join(packageRoot, 'prisma', 'migrations');
const extraSqlDir = join(packageRoot, 'prisma', 'sql');

/** A fixed name: this migration is the repository's starting point, not a timestamp race. */
const MIGRATION_NAME = '20260910000000_init';

function main(): void {
  const target = join(migrationsDir, MIGRATION_NAME);

  if (existsSync(join(target, 'migration.sql'))) {
    console.log(`Migration ${MIGRATION_NAME} already exists — nothing to do.`);
    console.log('To rebuild it, delete the folder first (only safe before it has been applied anywhere).');
    return;
  }

  // Count migration directories only: `migration_lock.toml` lives beside them.
  const applied = existsSync(migrationsDir)
    ? readdirSync(migrationsDir, { withFileTypes: true }).filter((d) => d.isDirectory() && d.name !== MIGRATION_NAME)
    : [];
  if (applied.length > 0) {
    throw new Error(
      `Refusing to create an initial migration: ${applied.length} migration(s) already exist. ` +
        'Use `prisma migrate dev` for subsequent changes.',
    );
  }

  console.log('Generating table DDL from the schema (offline, no database needed)...');
  // Run Prisma's own JS entry point with the current Node binary. Spawning `npx.cmd`
  // fails on Node 22+ for Windows (.cmd files need a shell since the CVE-2024-27980
  // fix), and routing through a shell would bring back quoting problems.
  const requireFromHere = createRequire(import.meta.url);
  const prismaPackage = requireFromHere('prisma/package.json') as { bin: { prisma: string } };
  const prismaEntry = join(dirname(requireFromHere.resolve('prisma/package.json')), prismaPackage.bin.prisma);
  const generated = execFileSync(
    process.execPath,
    // Prisma 7 flag names: `--to-schema` (the older `--to-schema-datamodel` is gone).
    [prismaEntry, 'migrate', 'diff', '--from-empty', '--to-schema', 'prisma/schema.prisma', '--script'],
    { cwd: packageRoot, encoding: 'utf8', maxBuffer: 32 * 1024 * 1024 },
  );

  const extras = readdirSync(extraSqlDir)
    .filter((f) => f.endsWith('.sql'))
    .sort()
    .map((f) => ({ name: f, sql: readFileSync(join(extraSqlDir, f), 'utf8') }));

  const banner = [
    '-- Initial migration for the Max Fitness Platform.',
    '--',
    '-- Part 1 is generated from prisma/schema.prisma.',
    '-- Part 2 is hand-written SQL from prisma/sql/, which Prisma cannot express:',
    '-- partial unique indexes, CHECK constraints, the v_member_fee read model, and',
    '-- Row Level Security on every table (ADR-011). Do not edit this file after it',
    '-- has been applied anywhere — create a new migration instead.',
    '',
  ].join('\n');

  const parts = [
    banner,
    '-- ═══ Part 1: generated from schema.prisma ═══',
    '',
    generated.trim(),
    '',
    ...extras.flatMap((e) => ['', `-- ═══ Part 2: prisma/sql/${e.name} ═══`, '', e.sql.trim(), '']),
  ];

  mkdirSync(target, { recursive: true });
  writeFileSync(join(target, 'migration.sql'), `${parts.join('\n')}\n`, 'utf8');

  const lines = parts.join('\n').split('\n').length;
  console.log(`Wrote prisma/migrations/${MIGRATION_NAME}/migration.sql (${lines} lines)`);
  console.log(`  generated DDL:  ${generated.trim().split('\n').length} lines`);
  for (const e of extras) {
    console.log(`  ${e.name}: ${e.sql.trim().split('\n').length} lines`);
  }
  console.log('\nNext: pnpm db:migrate');
}

main();
