import { CALL_TASK_PRIORITY, type Clock, type FeeState, type ISTDate, type MemberStatus } from '@mfp/shared';
import { attendanceDateOf, cooldownDecision, type CooldownDecision } from '../attendance/cooldown';
import { shouldCreateExpiredButVisiting } from '../calls/call-task.rules';
import { DomainError } from '../errors';
import { assertCan, type CrmActor } from './permissions';

/**
 * Marking attendance by hand at the desk (crm-ux-blueprint §11; BR-9.4).
 *
 * Until the kiosk exists, this is how every visit is recorded, so it has to survive a
 * busy counter. Two different repeats are collapsed: the same member walking past twice
 * inside the cooldown is one visit (BR-9.1, the same rule the kiosk will use), and the
 * same tap arriving twice — a double press, a retried request — is recognised by its
 * `clientEventId` and writes nothing (CLAUDE.md §2.5).
 *
 * Undo does not delete the row; it voids it. Every read already ignores voided events,
 * and a correction that leaves no trace is not a correction.
 */

export interface MemberForAttendance {
  readonly id: string;
  readonly status: MemberStatus;
  /** The member's most recent non-voided check-in, which the cooldown is measured from. */
  readonly lastAttendanceAt: Date | null;
}

export interface AttendanceEventRecord {
  readonly gymId: string;
  readonly memberId: string;
  readonly clientEventId: string;
  readonly method: 'MANUAL';
  readonly capturedAt: Date;
  /** BR-9.2: the IST calendar day the visit counts for. */
  readonly attendanceDate: ISTDate;
  readonly recordedById: string;
  /** What the desk could see at the time; the follow-up rules read it later (BR-9.3). */
  readonly feeStateAtCheckIn: FeeState | null;
}

export interface StoredAttendanceEvent {
  readonly id: string;
  readonly gymId: string;
  readonly memberId: string;
  readonly voidedAt: Date | null;
}

/** The priority-1 call for a member who walked in with their fees run out (BR-7). */
export interface CallTaskToRaise {
  readonly gymId: string;
  readonly memberId: string;
  readonly reason: 'EXPIRED_BUT_VISITING';
  readonly priority: number;
  readonly dueDate: ISTDate;
}

export interface AttendanceStore {
  memberForAttendance(gymId: string, memberId: string): Promise<MemberForAttendance | null>;
  /** True when this tap has already been stored — the request was retried. */
  hasEventId(clientEventId: string): Promise<boolean>;
  createEvent(record: AttendanceEventRecord): Promise<string>;
  loadEvent(gymId: string, eventId: string): Promise<StoredAttendanceEvent | null>;
  voidEvent(eventId: string, at: Date): Promise<void>;
  /** `false` when an open task of this reason already exists for the member. */
  raiseCallTask(task: CallTaskToRaise): Promise<boolean>;
}

export interface AttendanceUnitOfWork {
  transaction<T>(work: (store: AttendanceStore) => Promise<T>): Promise<T>;
}

export interface MarkAttendanceResult {
  readonly decision: CooldownDecision;
  /** `null` when nothing was written, so the screen can say "already marked". */
  readonly eventId: string | null;
  /** True when this visit put the member on the call list as `EXPIRED_BUT_VISITING`. */
  readonly callTaskRaised: boolean;
}

export async function markAttendance(
  input: {
    readonly memberId: string;
    /** Generated by the screen, so a double tap is one visit, not two. */
    readonly clientEventId: string;
    readonly feeStateAtCheckIn?: FeeState;
  },
  deps: {
    readonly actor: CrmActor;
    readonly clock: Clock;
    readonly uow: AttendanceUnitOfWork;
    /** `attendance.checkInCooldownMinutes` from settings (BR-9.1). */
    readonly cooldownMinutes: number;
  },
): Promise<MarkAttendanceResult> {
  const now = deps.clock.now();
  assertCan(deps.actor, 'attendance.manual', now);

  return deps.uow.transaction(async (store) => {
    const member = await store.memberForAttendance(deps.actor.gymId, input.memberId);
    if (member === null) throw new DomainError('NOT_FOUND', 'No such member');

    // BR-9.4: staff can mark anyone standing in front of them, whatever their status —
    // the kiosk's eligibility rules (BR-9.5) are about faces, not about people.
    const decision = cooldownDecision({
      capturedAt: now,
      lastAttendanceAt: member.lastAttendanceAt,
      cooldownMinutes: deps.cooldownMinutes,
      isDuplicateEventId: await store.hasEventId(input.clientEventId),
    });
    if (decision !== 'RECORD') return { decision, eventId: null, callTaskRaised: false };

    const eventId = await store.createEvent({
      gymId: deps.actor.gymId,
      memberId: member.id,
      clientEventId: input.clientEventId,
      method: 'MANUAL',
      capturedAt: now,
      attendanceDate: attendanceDateOf(now),
      recordedById: deps.actor.staffUserId,
      feeStateAtCheckIn: input.feeStateAtCheckIn ?? null,
    });

    // BR-7 / BR-9.3: someone still turning up after their fees ran out is the warmest lead
    // the gym has. Only a visit that was actually recorded counts, and the database keeps
    // it to one open task per member.
    const feeState = input.feeStateAtCheckIn;
    const callTaskRaised =
      feeState !== undefined && shouldCreateExpiredButVisiting({ feeStateAtCheckIn: feeState, memberStatus: member.status })
        ? await store.raiseCallTask({
            gymId: deps.actor.gymId,
            memberId: member.id,
            reason: 'EXPIRED_BUT_VISITING',
            priority: CALL_TASK_PRIORITY.EXPIRED_BUT_VISITING,
            dueDate: attendanceDateOf(now),
          })
        : false;

    return { decision, eventId, callTaskRaised };
  });
}

/** The undo bar behind a mistaken tap (crm-ux-blueprint §11). */
export async function undoAttendance(
  input: { readonly eventId: string },
  deps: { readonly actor: CrmActor; readonly clock: Clock; readonly uow: AttendanceUnitOfWork },
): Promise<{ readonly memberId: string }> {
  const now = deps.clock.now();
  assertCan(deps.actor, 'attendance.manual', now);

  return deps.uow.transaction(async (store) => {
    const event = await store.loadEvent(deps.actor.gymId, input.eventId);
    if (event === null) throw new DomainError('NOT_FOUND', 'No such check-in');
    if (event.voidedAt !== null) throw new DomainError('CONFLICT', 'This check-in was already taken back');

    await store.voidEvent(event.id, now);
    return { memberId: event.memberId };
  });
}
